name: Day2-learnig about the checkout function

on:
  workflow_dispatch: 

jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositery
        uses: actions/checkout@v2

      - name: List Files
        run: ls
        
      - name: Print Currrent Working Directory
        run: pwd
       
      
