name: Day 3- Variables

on:
 workflow_dispatch: 

jobs:
  variable-job:
    runs-on: ubuntu-latest
    env:
      app_name: my-devops-app
      environment: dev
    steps:
      - name: Print variables
        run: |
         echo "This is my $app_name"
         echo "This is my $environment"
      - name: secret
        run: |
          echo "This is my ${{secrets.MY_SECRET}}"
          
      
      

 
