name: day-9-Docker bulid

on: 
  workflow_dispatch: 

jobs:
  docker-bulid:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Code
        uses: actions/checkout@v4

      - name: Bulid Docker images
        run: docker bulid -t my-first-image.

      - name: Run Docker container
        run:  docker run  my-first-image
        
      
